---
title:               asgeo1
tagline:             "Adam George: Software developer, guitarist, and \"micropreneur\""
login:               <%= ENV["obtvse_login"]    ? ENV["obtvse_login"]    : "username" %>
password:            <%= ENV["obtvse_password"] ? ENV["obtvse_password"] : "password" %>
name:                Adam George
twitter:             asgeo1
github:              asgeo1
stackoverflow:       '172973/asgeo1'
email:               <%= ENV["obtvse_email"]    ? ENV["obtvse_email"]    : "email" %>
google_analytics_id: UA-31926293-1
